# Generated by Django 4.2.1 on 2023-05-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_chatbron_date_message_alter_chatbron_date_v_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbron',
            name='date_message',
            field=models.DateField(verbose_name='Дата отправки сообщения'),
        ),
        migrations.AlterField(
            model_name='chatbron',
            name='date_v',
            field=models.DateField(verbose_name='Дата выезда'),
        ),
        migrations.AlterField(
            model_name='chatbron',
            name='date_z',
            field=models.DateField(verbose_name='Дата заезда'),
        ),
        migrations.AlterField(
            model_name='chatbron',
            name='name_tur',
            field=models.CharField(choices=[('US', 'United States'), ('FR', 'France'), ('CN', 'China'), ('RU', 'Russia'), ('IT', 'Italy')], max_length=250, verbose_name='Название путевки'),
        ),
    ]
