# Generated by Django 4.2.1 on 2023-05-23 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_chatbron_name_tur_alter_chatbron_number_human'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbron',
            name='name_tur',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be Alphanumeric', regex='^[a-z]*$')], verbose_name='Название путевки'),
        ),
    ]
