# Generated by Django 4.2.1 on 2023-05-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_chat_id_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatPrivate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1_id', models.CharField(max_length=50, verbose_name='Идентификатор пользователя')),
                ('user2_id', models.CharField(max_length=50, verbose_name='Идентификатор администратора')),
                ('full_text', models.TextField(verbose_name='Сообщение')),
                ('date', models.DateTimeField(verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'ОбщийЧат',
                'verbose_name_plural': 'ОбщиеЧаты',
            },
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='id_user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
    ]
