# Generated by Django 4.2.1 on 2023-05-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_chatprivate_uploadfile_rename_id_user_chat_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50)),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ОбщийЧат',
                'verbose_name_plural': 'ОбщиеЧаты',
            },
        ),
    ]
