# Generated by Django 4.2.1 on 2023-06-01 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_uploadfiledoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppProf1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be Alphanumeric', regex='^[а-я]*$')], verbose_name='Фамилия пользователя')),
                ('first_name', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be Alphanumeric', regex='^[а-я]*$')], verbose_name='Имя')),
                ('father_name_user_ap', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be Alphanumeric', regex='^[а-я]*$')], verbose_name='Отчество')),
                ('job_title', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username must be Alphanumeric', regex='^[а-я]*$')], verbose_name='Должность')),
                ('number_phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^[0-9]*$')], verbose_name='Номер телефона')),
                ('uploaded_at1', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
