# Generated by Django 4.2.1 on 2023-06-01 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_appprof1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
