# Generated by Django 4.2.1 on 2023-06-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_alter_chatbron_date_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatprivate',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
